# Generated by Django 6.0.2 on 2026-02-22 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSubtopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='exam_board',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='related_subjects',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_studied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='exam_board',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='response_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_board',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AddField(
            model_name='subjectmodule',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='key_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(related_name='skill_questions', to='content.skill'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='key_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modules',
            field=models.ManyToManyField(through='content.SubjectModule', to='content.module'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectmodule',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name', 'exam_board'), name='unique_module_name_per_board'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('slug', 'exam_board'), name='unique_module_slug_per_board'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'exam_board'), name='unique_subject_name_per_board'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('slug', 'exam_board'), name='unique_subject_slug_per_board'),
        ),
        migrations.AddField(
            model_name='modulemastery',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module'),
        ),
        migrations.AddField(
            model_name='modulemastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulesubtopic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='content.module'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopics',
            field=models.ManyToManyField(related_name='subtopic_questions', to='content.modulesubtopic'),
        ),
        migrations.AddField(
            model_name='modulesubtopicmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulesubtopicmastery',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.modulesubtopic'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.skill'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='modulemastery',
            unique_together={('student', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='modulesubtopic',
            unique_together={('module', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modulesubtopicmastery',
            unique_together={('student', 'submodule')},
        ),
        migrations.AlterUniqueTogether(
            name='skillmastery',
            unique_together={('student', 'skill')},
        ),
    ]
