import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom-navbar";
import  { CustomSidebar } from "@/components/custom-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { CustomNavigationMenu, NavigationMenuDemo } from "@/components/custom-nagivation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Tutorio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CustomNavigationMenu />
            <div>
              {children}
            </div>

      </body>
    </html>
  );
}
